# Generated by Django 4.1.7 on 2023-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighboursDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, choices=[('Южный', 'Южный'), ('Левада', 'Левада'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный')], max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Расстояние между соседями',
                'verbose_name_plural': 'Расстояния между соседями',
            },
        ),
    ]
