# Generated by Django 4.1.7 on 2023-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighboursdistance',
            name='finish',
            field=models.CharField(blank=True, choices=[('Южный', 'Южный'), ('Левада', 'Левада'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный')], max_length=100),
        ),
    ]
