# Generated by Django 4.1.7 on 2023-06-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_neighboursdistance_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighboursdistance',
            name='finish',
            field=models.CharField(blank=True, choices=[('Южный', 'Южный'), ('Левада', 'Левада'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Лубны', 'Лубны'), ('Купянск', 'Купянск'), ('Лубны-2', 'Лубны-2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='neighboursdistance',
            name='start',
            field=models.CharField(blank=True, choices=[('Южный', 'Южный'), ('Левада', 'Левада'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Лубны', 'Лубны'), ('Купянск', 'Купянск'), ('Лубны-2', 'Лубны-2')], max_length=100),
        ),
    ]
