# Generated by Django 4.1.7 on 2023-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0004_delete_neighboursdistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighboursDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, choices=[('Южный', 'Южный'), ('Левада', 'Левада'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Лубны', 'Лубны'), ('Купянск', 'Купянск'), ('Лубны-2', 'Лубны-2'), ('Лубны-3', 'Лубны-3')], max_length=100)),
                ('finish', models.CharField(blank=True, choices=[('Южный', 'Южный'), ('Левада', 'Левада'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Центральный', 'Центральный'), ('Лубны', 'Лубны'), ('Купянск', 'Купянск'), ('Лубны-2', 'Лубны-2'), ('Лубны-3', 'Лубны-3')], max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Расстояние между соседями',
                'verbose_name_plural': 'Расстояния между соседями',
            },
        ),
    ]
