# Generated by Django 4.1.7 on 2023-06-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_neighboursdistance_finish_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeighboursDistance',
        ),
    ]
