# Generated by Django 4.1.7 on 2023-06-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railway', '0005_railwaystations_status'),
        ('routes', '0007_delete_neighboursdistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighboursDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Расстояние, км')),
                ('finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finishpoint', to='railway.railwaystations', verbose_name='Конечный пункт')),
                ('start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startpoint', to='railway.railwaystations', verbose_name='Начальный пункт')),
            ],
            options={
                'verbose_name': 'Расстояние между соседями',
                'verbose_name_plural': 'Расстояния между соседями',
            },
        ),
    ]
