# Generated by Django 4.1.7 on 2023-05-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='railwaystations',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railwaystations', to='railway.cities', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('status', models.CharField(blank=True, choices=[], max_length=100)),
                ('stations', models.ManyToManyField(blank=True, related_name='stations', to='railway.railwaystations', verbose_name='станции')),
                ('train_begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='railwaystations_begin', to='railway.railwaystations', verbose_name='Станция отправления')),
                ('train_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='railwaystations_end', to='railway.railwaystations', verbose_name='Станция прибытия')),
            ],
            options={
                'verbose_name': 'Поезд',
                'verbose_name_plural': 'Поезда',
            },
        ),
    ]
