# Generated by Django 4.1.7 on 2023-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_railwaystations_neighbours_alter_trains_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaystations',
            name='neighbours',
            field=models.ManyToManyField(blank=True, to='railway.railwaystations', verbose_name='соседние станции'),
        ),
    ]
