# Generated by Django 4.1.7 on 2023-06-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_alter_railwaystations_neighbours'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaystations',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
