# Generated by Django 4.1.7 on 2023-06-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0007_trainstatus_speed_alter_trains_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='status',
            field=models.CharField(blank=True, choices=[('Экспресс', 'Экспресс'), ('Скоростной', 'Скоростной'), ('Электропоезд', 'Электропоезд')], max_length=100),
        ),
        migrations.CreateModel(
            name='RailwayStationsTrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='railwaystations_trains', to='railway.railwaystations', verbose_name='Станция')),
                ('trains', models.ManyToManyField(blank=True, null=True, to='railway.trains', verbose_name='проходящие поезда')),
            ],
            options={
                'verbose_name': 'Поезда через вокзал',
                'verbose_name_plural': 'Поезда через вокзалы',
                'default_related_name': 'railwaystations_trains',
            },
        ),
    ]
