# Generated by Django 4.1.7 on 2023-06-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0008_alter_trains_status_railwaystationstrains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaystations',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='city', to='railway.cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='railwaystationstrains',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='railwaystations_trains', to='railway.railwaystations', verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='trains',
            name='train_begin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='railwaystations_begin', to='railway.railwaystations', verbose_name='Станция отправления'),
        ),
        migrations.AlterField(
            model_name='trains',
            name='train_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='railwaystations_end', to='railway.railwaystations', verbose_name='Станция прибытия'),
        ),
    ]
