# Generated by Django 4.1.7 on 2023-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_alter_railwaystations_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ранг билета',
                'verbose_name_plural': 'Ранги билета',
            },
        ),
    ]
