# Generated by Django 4.1.7 on 2023-06-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0010_ticketranks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата поездки')),
                ('date_bought', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('rank', models.CharField(choices=[], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_finish', to='railway.railwaystations', verbose_name='Станция отправления')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_start', to='railway.railwaystations', verbose_name='Станция отправления')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_train', to='railway.trains', verbose_name='Поезд')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
