# Generated by Django 4.1.7 on 2023-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0011_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketranks',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rank',
            field=models.CharField(choices=[('Общий', 'Общий'), ('Плацкартный', 'Плацкартный'), ('Купейный', 'Купейный'), ('СВ', 'СВ')], max_length=100),
        ),
    ]
