# Generated by Django 4.1.7 on 2023-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0012_ticketranks_description_alter_ticket_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
