# Generated by Django 4.1.7 on 2023-06-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0015_alter_railwaystationstrains_trains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_train', models.DateTimeField(verbose_name='Дата')),
                ('tickets', models.ManyToManyField(blank=True, related_name='tickets_train', to='railway.ticket', verbose_name='Билеты')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_train', to='railway.trains', verbose_name='Поезд')),
            ],
        ),
    ]
