# Generated by Django 4.1.7 on 2023-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0016_scheduletrains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletrains',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание поездов'},
        ),
        migrations.AddField(
            model_name='scheduletrains',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
