# Generated by Django 4.1.7 on 2023-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0018_rename_vaggon_ticket_carriage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_start',
            field=models.DateTimeField(blank=True, verbose_name='Дата поездки'),
        ),
    ]
