# Generated by Django 4.1.7 on 2023-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0019_alter_ticket_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поездки'),
        ),
    ]
