# Generated by Django 4.1.7 on 2023-06-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0021_alter_scheduletrains_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_train', to='railway.trains', verbose_name='Поезд'),
        ),
    ]
