# Generated by Django 4.1.7 on 2023-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0022_alter_ticket_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
