# Generated by Django 4.1.7 on 2023-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0023_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketranks',
            name='koef',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Коэффиецинт'),
        ),
    ]
