# Generated by Django 4.1.7 on 2023-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0027_scheduletrains_decription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletrains',
            name='date_train',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='scheduletrains',
            name='decription',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
