# Generated by Django 4.1.7 on 2023-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0028_alter_scheduletrains_date_train_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletrains',
            name='time_train',
            field=models.TimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
