# Generated by Django 4.1.7 on 2023-07-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0030_remove_ticket_on_sale_ticket_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_train', to='railway.scheduletrains', verbose_name='Поезд'),
        ),
    ]
